version: '3'

services:
    postgres:
      image: 'postgres:12.2'
      container_name: 'shoppinglist-postgres'
      ports:
        - 5432:5432
      networks: 
        - postgres-network
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=shoppinglist
      volumes:
        - ./data/pgdata:/var/lib/postgresql/data
    pgadmin:
      image: thajeztah/pgadmin4
      container_name: 'shoppinglist-pgadmin'
      networks:
        - postgres-network
      ports:
        - 5050:5050
networks:
  postgres-network:
    driver: bridge
